version: '3.7'


services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
        ports:
            - 9200:9200
        volumes:
            - /usr/share/elasticsearch/data
            - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        environment:
            discovery.type: single-node
            ES_JAVA_OPTS: "-Xmx256m -Xms256m"
            network.publish_host: _eth0_
        ulimits:
            memlock:
                soft: -1
                hard: -1


    logstash:
        image: docker.elastic.co/logstash/logstash:7.16.2
        ports:
            - 5000:5000
        volumes:
            - ./logstash/pipeline:/usr/share/logstash/pipeline
            - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
        depends_on:
            - elasticsearch


    kibana:
        image: docker.elastic.co/kibana/kibana:7.16.2
        ports:
           - 5601:5601
        environment:
            ELASTICSEARCH_URL: "http://localhost:9200"
            ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"  
            elasticsearch.ssl.verificationMode: none  
        volumes:
            - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
        depends_on:
            - elasticsearch

